version: '3'

services:
  traffic-analyzer:
    image: traffic-analyzer:latest
    environment:
      - DEBUG=false
      - LOG=tlir
      - MONGO_DB_HOST=mongodb://mongo:27017
      - MONGO_DB_NAME=database
      - MONGO_DB_USER=user
      - MONGO_DB_PASSWORD=password
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
